/**
 * How to build:    $  ./make.sh database/2022/2022.3170411/_cover.typ
 */


#import "/template/preprint-cover-v1.H.typ": *
#make_cover(
  toml("info.toml"),
  title_override: [
    Fake Journal $"Fake"="Rand"("data")^2$ Typesetting Demo Dummy Article Generated by Some LLM
  ],
  abstract_content: [
    The increasing deployment of autonomous sensing systems in urban and industrial environments has motivated renewed interest in distributed morphological computation. This thesis investigates how local geometric adaptation in sensor arrays may improve resilience, energy efficiency, and environmental observability. While most prior architectures rely on centralized coordination, the present work evaluates decentralized control laws inspired by swarm intelligence and adaptive topology optimization...
  ],
)




