imgurl = """https://images.unsplash.com/photo-1560148271-00b5e5850812?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dCUyMHJleHxlbnwwfHwwfHx8Mg%3D%3D"""


[en]
href = "/en/submit-guide/"
title = """
Why not untruth?
"""

desc = """
Ready to submit a parody “research” manuscript? FAKE JOURNAL is a satire academic journal for playful scholars who love fake data, absurd methods, and overconfident conclusions. Contribute your funniest paper, join the community of critical comedians, and help turn the conventions of academic publishing into the punchline.
"""



[zh]
href = "/zh/submit-guide/"
title = """
为什么不来点「不实」？
"""

desc = """
准备好投稿一篇戏仿“研究”手稿了吗？FAKE JOURNAL 是一本面向爱搞笑的学术期刊，用来刊登讽刺性的论文：会故意编造数据、用离谱的方法，最后还要一本正经地得出荒诞结论。贡献你最搞的论文，加入这个质疑型“学术喜剧”社区，让学术出版的传统成为笑点。
"""


