account_id = "6dc2ede68aff1ac4f25aecdab3b62a4c"
name = "fakejournal"
main = "./src/index.js"

compatibility_date = "2026-05-05"
assets = { directory = "../wwwdist" }

[[d1_databases]]
binding = "DB" # 对应代码中的 env.DB
database_name = "fakejournalmain_db"
database_id = "131e1713-5bb9-4acd-9ac8-7b18fa0a133e"
