[issue]
issue_serial = "PRE(1)"
issue_volume = "2022.01"
year = "2022"
subclass = ""
editors = "Physhan|Neruthes"
draft = false

cover_story_title = """Martian Biosignatures: Indicators of life"""
cover_story_id = """2022.1170411"""


[[article]]
path = "database/2022/2022.3170411"
range_from = 5
range_to = 6

[[article]]
path = "database/2022/2022.3170411"
range_from = 8
range_to = 9
